### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by dadav** [dadav/helm-schema#1]
There are no tests yet.

**Comment by dadav** [comment]
Made some progress https://github.com/dadav/helm-schema/commit/cfd42a3fc0987d496f120d3891e7e1d78098a160

**Comment by outofrange** [comment]
I think a set of end-to-end tests, specifying `values.yaml` as input, `expected.schema.json` as output, would help a lot.
Wouldn't be too much of a hassle, both in setting up and maintaining - a bunch of real(ish) values could be gathered and initially rendered to pin the output for future `jq diffs`.
