### ISSUE TITLE
how to keep the original order of the yaml keys in the generated json schema?

### ISSUE THREAD

**Issue by michael2008** [dadav/helm-schema#102]
The problem is that the generated json schema appears to have different key order from the orginal yaml.
When I input the json schema to UI lib such as https://rjsf-team.github.io/react-jsonschema-form/, I want to keep the original key order.
Is it because the golang json lib does not preserve order?
Can you please fix this?

**Comment by dadav** [comment]
I don't think I can fix this here. Check out https://rjsf-team.github.io/react-jsonschema-form/docs/usage/objects/#specifying-property-order
