### ISSUE TITLE
Required in properties/items blocks not being applied

### ISSUE THREAD

**Issue by baptman21** [dadav/helm-schema#20]
# Description

When defining the schema in `properties` or `items` and setting the properties as required, it does not mark them as required in the generated schema.

## Example

```yaml
# values.yaml
# @schema
# type: object
# description: example
# additionalProperties: false
# properties:
#   name:
#     type: string
#     required: true
#   value:
#     type: string
#     required: true
# @schema
example: null
```

```
helm-schema values.yaml
```

Generated schema
```json
{
  "additionalProperties": false,
  "properties": {
    "example": {
      "additionalProperties": false,
      "default": "null",
      "properties": {
        "name": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "description": "example",
      "title": "example",
      "type": "object"
    },
    "global": {
      "description": "Global values are values that can be accessed from any chart or subchart by exactly the same name.",
      "title": "global",
      "type": "object"
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object"
}
```

As you can see the `name` and `value` are not required in the `example` object, which makes the following value file correct:

```
example:
  value: hello
```

## More information

It might be due to the fact that my property is null but I also have the problem when defining objects in an empty list using `items`. Maybe because it is a complete schema the required true is not processed ?
I tried to add a `required` list like it is expected in the json schema but with the validation `required` needs to be a bool.

A possible mitigation is to define the properties of the objects, but for a list (using `items`) it means having one element in the list by default, which is not ideal every time.

If the behavior is actually expected and I missed something in the doc forgive me.

# Version

```
helm-schema -v
helm-schema version 0.10.0
```

PS: thank you very much for this repo this tool is amazing to make schemas in helm charts not a nightmare :pray:

**Comment by dadav** [comment]
Thanks for your report, I'll have a look at it! :)
