### ISSUE TITLE
order matters when type is an array and generating defaults

### ISSUE THREAD

**Issue by snuggie12** [dadav/helm-schema#37]
I'm not sure if this is specific types, but given:
```
# values.yaml
# note the default is null (not my code so no clue why it's null)
# but the ordering is integer first

    # @schema
    # type: [integer, null]
    # @schema
    # -- (int) Maximum number of requests before triggering the circuit breaking
    maxRequests:
```

If you don't skip `default` this happens:
```
$ helm-schema -n -k additionalProperties,description,required,title -o foo.json -l trace
FATA[2024-08-05T16:43:03-07:00] Error while converting  to integer: strconv.Atoi: parsing "": invalid syntax
```

I thought this might be specific to `null` but it also occurs in this case:
```
    # @schema
    # type: [integer, string]
    # @schema
    # -- CPU Limits is tricky. Set to double your requests, and make sure you aren't seeing throttling.
    cpu: 600m
```

However with a more helpful log message:
```
FATA[2024-08-05T16:45:33-07:00] Error while converting 600m to integer: strconv.Atoi: parsing "600m": invalid syntax
```

As mentioned, this only happens if you don't skip printing the defaults so it's almost certainly located around that part of the code.

I don't know if it's possible, but if the key or line number which caused it to fatal could be printed that'd be great too.

**Comment by dadav** [comment]
Hi @snuggie12,

thanks for your report. Problem is here: https://github.com/dadav/helm-schema/blob/main/pkg/schema/schema.go#L627

Gonna fix this asap.
