### ISSUE TITLE
`---` gets ignored, possibly including comments from the previous YAML document

### ISSUE THREAD

**Issue by outofrange** [dadav/helm-schema#49]
```yaml
# Previous YAML document
---
# -- Some comment
foo: bar
```

results in `"description": "Previous document\nSome comment"`, while I'd expect `"description": "Some comment"`.

I'm actually a bit surprised that `---` "document borders" seem to be completely ignored here, but
- I only noticed this because of #47
- it wouldn't be an issue after fixing #48
- I can't think of a reason to have multiple documents with data in _values.yaml_ (empty documents should be fine and expected because of one of the _yamllint_ default rules [document_start](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_start))
- I'm not even sure how _helm_ handles _values.yaml_ with data in multiple documents

But wanted it to document anyway, maybe there are other issues with `---` as well.

Edit: Using newest helm-schema version 0.12.0.

**Comment by outofrange** [comment]
Played around a bit more - `--- gets ignored` doesn't seem to be true in all cases, weirdly enough...


```yaml
# -- Description in first document
keyFirstDoc: foo

# Previous document
---
# -- Description in second document
keySecondDoc: bar
```

generates the schema only **until** `---`, ignoring everything after?

```json
{
  "additionalProperties": false,
  "properties": {
    "global": {
      "description": "Global values are values that can be accessed from any chart or subchart by exactly the same name.",
      "title": "global",
      "type": "object"
    },
    "keyFirstDoc": {
      "default": "foo",
      "description": "Description in first document",
      "title": "keyFirstDoc",
      "type": "string"
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "keyFirstDoc"
  ]
}
```

**Comment by dadav** [comment]
I've never considered a case eith multiple documents in a single values.yaml. Is this even possible? Is it used often?

**Comment by dadav** [comment]
So apparently yaml.v3 [...decodes the first document found within the in byte slice only](https://pkg.go.dev/gopkg.in/yaml.v3#Unmarshal).

In case of 

```yaml
# foo
---
bar: 1
```

the first comment is not considered a valid document and gets added to the HeadComment field of the next parsed yaml.Node. The literal `---` is not part of the HeadComment and thats why we can't detect it manually :(
