### ISSUE TITLE
Distribute as Docker Image

### ISSUE THREAD

**Issue by mircea-pavel-anton** [dadav/helm-schema#63]
It would be helpful to also distribute this tool as a docker image.

Given that there is already a `.goreleaser.yaml` config in place, we can also make use of it to build and push docker images to `ghcr.io` and/or `docker.io`

I can fork and PR these changes if you'd be willing to review and merge them!

**Comment by dadav** [comment]
Thanks for the suggestion. I'll add this.

**Comment by mircea-pavel-anton** [comment]
@dadav thank you for adding this feature!

Is there any reason for not providing a multi-arch image? We could have at least an amd64 and an arm64 variant at least imho and then group them under a shared manifest
