### ISSUE TITLE
Can't use relative $ref inside of patternProperties

### ISSUE THREAD

**Issue by snuggie12** [dadav/helm-schema#74]
While testing out the new relative path for `$ref` change you made for me, we ran into an issue. Given this annotation:

```
+# @schema
+# type: object
+# patternProperties:
+#   "^.*":
+#     $ref: apps-subschema.json#/app
+# @schema
```

We got the following error:

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
foo:
Reference /apps-subschema.json#/app must be canonical
```

Reading through the json schema documentation this makes sense. I didn't know if it'd be possible to put some sort of helper function which expands the `$ref` into `patternProperties` like how it works as a standalone annotation.

**Comment by dadav** [comment]
Hi snuggie12, thanks for your report, I'll look into this issue asap.
