### ISSUE TITLE
Schema from CRDs

### ISSUE THREAD

**Issue by lucacome** [dadav/helm-schema#75]
We have CRDs in our project and the fields are exposed through values in helm. 
Would it be possible to get the schema from the CRDs and maybe link it as a ref? Or automatically add it to the `values.yaml` so I don't have to keep them in sync manually?

I mean technically possible/fairly easy to implement. Has anybody tried to do something like this?

**Comment by dadav** [comment]
Hi lucacome, interesting idea, but I don't know if this is a usecase for helm-schema..

**Comment by lucacome** [comment]
yeah it probably isn't. Maybe another project that could integrate with this one somehow.
