### ISSUE TITLE
Length of array

### ISSUE THREAD

**Issue by krzysztof-magosa** [dadav/helm-schema#80]
Hi.
At the beginning - big thanks for your project, it's really helpful.

I'm using helm-schema for quite complicated use-cases, and found one limitation, which does not seem to exist in JSON Schema standard. I would like to make some arrays required in a sense, that there must be at least one item. From what I've found, in JSON Schema this can be achieved by `minItems` parameter. Could this be added here as well?

https://json-schema.org/understanding-json-schema/reference/array#length

Thanks again,
KM.

**Comment by dadav** [comment]
Hi, thats a nice idea. I'll add this.
